# This is a basic workflow to help you get started with Actions
name: Deploy with Capistrano

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch'
        default: 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    #    runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      ImageOS: ubuntu20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        # ruby-version: 3.0.1 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: get-deployment-config
      uses: actions/checkout@v3
      with:
        repository: $${{ secrets.CONFIG_REPO }} # repository containing deployment settings
        #  token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
        path:  deploy_config
    - name: copy-deployment-config
      run:  cp -r deploy_config/bioportal_web_ui/* .
    - uses: miloserdow/capistrano-deploy@master
      with:
        target: staging # Defines the environment that will be used for the deploymenhu
        #        BRANCH: master
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }} # Name of the variable configured in Settings/Secrets of your github project
